incLabel1 = ctk.CTkLabel(tabview.tab("Příjmy"), text = " ")
incLabel1.place(relwidth = 0.9, relheight = 0.1, relx = 0.05, rely = 0.11)
incLabel2 = ctk.CTkLabel(tabview.tab("Příjmy"), text = " ")
incLabel2.place(relwidth = 0.9, relheight = 0.1, relx = 0.05, rely = 0.22)
incLabel3 = ctk.CTkLabel(tabview.tab("Příjmy"), text = " ")
incLabel3.place(relwidth = 0.9, relheight = 0.1, relx = 0.05, rely = 0.33)
incLabel4 = ctk.CTkLabel(tabview.tab("Příjmy"), text = " ")
incLabel4.place(relwidth = 0.9, relheight = 0.1, relx = 0.05, rely = 0.44)
incLabel5 = ctk.CTkLabel(tabview.tab("Příjmy"), text = " ")
incLabel5.place(relwidth = 0.9, relheight = 0.1, relx = 0.05, rely = 0.55)
        
expLabel1 = ctk.CTkLabel(tabview.tab("Výdaje"), text = " ")
expLabel1.place(relwidth = 0.9, relheight = 0.1, relx = 0.05, rely = 0.11)
expLabel2 = ctk.CTkLabel(tabview.tab("Výdaje"), text = " ")
expLabel2.place(relwidth = 0.9, relheight = 0.1, relx = 0.05, rely = 0.22)
expLabel3 = ctk.CTkLabel(tabview.tab("Výdaje"), text = " ")
expLabel3.place(relwidth = 0.9, relheight = 0.1, relx = 0.05, rely = 0.33)
expLabel4 = ctk.CTkLabel(tabview.tab("Výdaje"), text = " ")
expLabel4.place(relwidth = 0.9, relheight = 0.1, relx = 0.05, rely = 0.44)
expLabel5 = ctk.CTkLabel(tabview.tab("Výdaje"), text = " ")
expLabel5.place(relwidth = 0.9, relheight = 0.1, relx = 0.05, rely = 0.55)

labels = [[incLabel1, incLabel2, incLabel3, incLabel4, incLabel5], [expLabel1, expLabel2, expLabel3, expLabel4, expLabel5]]
